### ISSUE TITLE
Ajout du support de CMake

### ISSUE THREAD

**Issue by romain-neil** [NazaraEngine/NazaraEngine#340]
Bonsoir,

cela serait bien d'ajouter le support de cmake, pour se passer de l'utilisation de Visual Studio.
Pas que je ne l'aime pas, mais je pense qu'il y a mieux que VS ou encore CodeBlocks

J'ai bien tenté d'utiliser un projet tel que 'cmake-converter' mais il semble qu'il y ait des effets de bord avec les différents scripts lua

Si razakel passe par là, je pense qu'il a les compétences nécessaires pour faire une ébauche du projet

Bien cordialement,

**Comment by selkij** [comment]
Bonsoir, vous pouvez utiliser xmake je me doute qu'il y ai un problème.

**Comment by romain-neil** [comment]
Je viens de tester un plugin xmake pour mon ide, et puisque il n'est plus mis à jour depuis 2018, il n'est plus compatible

**Comment by selkij** [comment]
Moi j'utilise xmake en terminal (sous debian10)

**Comment by SirLynix** [comment]
XMake est capable de générer un cmakelists que tu peux ouvrir dans l'IDE de ton choix, pas besoin de maintenir un cmakelists à la main.

Utilise `xmake project -k cmakelist`

**Comment by romain-neil** [comment]
effectivement, je viens de voir ça :) Merci

**Comment by romain-neil** [comment]
Bon, après un interminable chargement, cela m'indique que le type de projet (cmakelist) n'est pas supporté, si quelqu'un à une idée :/

> error: the project kind(cmakelist) is not supported!

Edit: je viens de voir ton issue Lynix

**Comment by SirLynix** [comment]
Le chargement est l'installation des packages, ça ne se fera qu'une fois.

Pour mon issue ce n'est pas vraiment lié, le problème ici c'est surtout sur j'ai mal écris la commande : `xmake project -k cmakelists` (il manquait le s)

**Comment by selkij** [comment]
Close?

**Comment by SirLynix** [comment]
Si @tutosfaciles48 confirme que le problème est réglé 😄

**Comment by waruqi** [comment]
> Je viens de tester un plugin xmake pour mon ide, et puisque il n'est plus mis à jour depuis 2018, il n'est plus compatible

Nous développons le nouveau plugin xmake-idea, soyez patient. Voici une version modifiée qui prend en charge la dernière idée/clion. https://github.com/dodola/xmake-idea

**Comment by romain-neil** [comment]
Super, merci tout le monde !
