### ISSUE TITLE
Liste des move problématiques

### ISSUE THREAD

**Issue by romain-neil** [NazaraEngine/NazaraEngine#343]
Bonjour,
je vais poster ici les différents move/passage de paramètres par copie, que je trouve ici.
Je met également certains move que clang tidy considère comme étant non nécessaires

- [x] ShaderNode/ShaderGraph.cpp: L414

 "trivially-copyable type":
- [x] src/Nazara/Physics2D/PhysWorld2D.cpp#L243
- [x] src/Nazara/Physics2D/RigidBody2D.cpp#L67

**Comment by SirLynix** [comment]
Pour le premier je le garde au cas où Qt ajouterait le mouvement par la suite, la logique est la même pour le reste, le mouvement non-nécessaire peut être utile par la suite si le type évolue (ou change) dans le futur au point de bénéficier du mouvement.

Ce qui serait vraiment intéressant par contre ce serait des std::move manquants, qui auraient été oubliés.

**Comment by romain-neil** [comment]
Oui, je suis en train de vérifier cela
