### ISSUE TITLE
Please add CMakeLists.txt

### ISSUE THREAD

**Issue by ghost** [NazaraEngine/NazaraEngine#400]

**Comment by SirLynix** [comment]
You can use xmake to generate a CMakeLists.txt if you wish.
`xmake project -k cmakelists`

**Comment by gvanem** [comment]
> xmake project -k cmakelists

Tried it:
```
...
to the local search directories:
  - brotli-v1.2.0.tar.gz, v1.2.0.tar.gz, brotli
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: error: pathspec '1.4.309+0' did not match any file(s) known to git
```

What the hell is this? I'll stick to my home-made GNU-makefiles instead of this Xmake crap.

**Comment by SirLynix** [comment]
That's an error related to a package that probably failed to download (hard to say without full log) which GNU make doesn't do btw.

Without full log I can't help you, could be an internet issue leading to this.
