### ISSUE TITLE
problems running physics demo

### ISSUE THREAD

**Issue by ghost** [NazaraEngine/NazaraEngine#401]
hey,

after compiling the code and trying out the physics demo i get error that nzsl.dll doesnt exsist.

**Comment by SirLynix** [comment]
Hello,

How do you run the physics demo? Using a Visual Studio project? `xmake run`?

**Comment by ghost** [comment]
so what i did is i cloned the project using github desktop (btw im on windows 10 22h2)
and then i ran:
`xmake`
`xmake project -k vs`
and then i opened the project in visual studio 2022 and pressed build from the right click menu on PhysicsDemo

**Comment by SirLynix** [comment]
So you're starting it via Visual Studio? Or running it outside of it?

It should work from Visual Studio

**Comment by ghost** [comment]
I tried both and both ways it didnt start im now going to retry it on another machine

**Comment by ghost** [comment]
working on it now 
![image](https://github.com/NazaraEngine/NazaraEngine/assets/118131071/f78102b1-b373-450b-818b-bae9455d166a)

**Comment by SirLynix** [comment]
You don't need to compile it before running the visual studio project generation (which will download all required packages as well).

**Comment by ghost** [comment]
ah so should i reclone it and do it all over again?

**Comment by SirLynix** [comment]
You don't need to, running `xmake` first will install dependencies for the current mode (debug by default) and then will compile the engine.

What I'm saying is that `xmake project -k vs` will install dependencies for all modes and then you will be able to compile using VS anyway.

**Comment by ghost** [comment]
ah i am now doing that i think i will improve the readme file to make it easier to get the engine up and running when i get it up and running and i will also update how the commands look like because they are outdated shown here;
![image](https://github.com/NazaraEngine/NazaraEngine/assets/118131071/a15037bc-ab3f-4ef5-8546-fd92164faeb0)

**Comment by ghost** [comment]
when i compile as debug i get this error:
![image](https://github.com/NazaraEngine/NazaraEngine/assets/118131071/1f5392aa-757a-47e3-aef9-49efd2611d81)
now getting a slightly different error
Physics2DDemo also gives me the same error
Also with PBR
unittests runs fine

release gives me this error:
![image](https://github.com/NazaraEngine/NazaraEngine/assets/118131071/33f564e0-04bd-4bc7-8840-97ef1d6a02c3)
releasebg gives me the same error as release.

**Comment by ghost** [comment]
i did get it working when i used `xmake run PhysicsDemo` but that is not a good idea if i want to ship a game with it....

**Comment by SirLynix** [comment]
Yeah this is intended for development, if you want to make a game with it you can have xmake copy all required dll (along with nzsl) with the `xmake install -o outputFolder` command. This is what the CI does.

**Comment by ghost** [comment]
thanks!
