### ISSUE TITLE
'ft2build.h' file not found

### ISSUE THREAD

**Issue by devalexxx** [NazaraEngine/NazaraEngine#412]
Bonjour, je n'arrive pas à compiler le moteur. Commande utilisée :

`
xmake build -j8
`

J'obtient la sortie suivante :
```
[ 60%]: cache compiling.debug src/Nazara/Utility/Formats/FreeTypeLoader.cpp
error: src/Nazara/Utility/Formats/FreeTypeLoader.cpp:7:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
  > in src/Nazara/Utility/Formats/FreeTypeLoader.cpp

```

J'ai essayé d'installer manuellement freetype, mais ça ne change rien.

- Macos Sonoma 14.1.2 arm64
- Clang 15.0.0

**Comment by SirLynix** [comment]
Hello.

Ça peut arriver si xmake pense trouver freetype sur le système alors qu'il manque les headers/libs de développement.

Est-ce que tu peux m'envoyer le log de `xmake f --check -vD` pour voir ce que ça donne ?

En attendant, la commande pour forcer xmake à installer freetype est `xmake require -f freetype`

**Comment by devalexxx** [comment]
Ça a fonctionner en forçant l'intallation de freetype merci.

**Comment by devalexxx** [comment]
J'ai parlé trop vite... 

Le moteur compile bien seul. Mais quand j'ajoute le package "nazaraengine" à mon projet j'obtient la même erreur (même en forçant l'installation de freetype).

xmake.lua :

```
add_repositories("nazara-repo https://github.com/NazaraEngine/xmake-repo.git")
add_requires("nazaraengine")

set_runtimes(is_mode("debug") and "MDd" or "MD")
set_languages("c++17")

target("Test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("nazaraengine", { components = { "graphics" }})
```

Voici la sortie de la commande `xmake f --check -vD` : https://pastebin.com/Gd4Lj9zr

**Comment by SirLynix** [comment]
Il faut installer toutes les versions de freetype demandées, y compris en debug et en release (tu peux faire un `xmake f --mode=debug` => `xmake require -f freetype` puis pareil mais en mettant le mode sur release), ou désinstaller la version brew. Je suis quand même curieux de savoir pourquoi la version brew ne fonctionne pas en tant que tel.

**Comment by SirLynix** [comment]
Hello, est-ce que le problème est toujours d'actualité ?

**Comment by devalexxx** [comment]
Salut, de mémoire c'était bon. J'ai essayer de tester mais j'ai des erreur à l'installation de nazara (en lien avec le dernier commit je crois)
`
build_0903f6c2/.gens/NazaraPhysics3D/macosx/unity_build/../../../../../src/Nazara/Physics3D/PhysWorld3D.cpp:405:76: error: non-virtual member function marked 'override' hides virtual member function
  405 |                         void OnStep(float inDeltaTime, JPH::PhysicsSystem& /*inPhysicsSystem*/) override
      |                                                                                                 ^
/Users/alspin/.xmake/packages/j/joltphysics/v5.2.0/2b4e0d7640294b148433eaa2af888e86/include/Jolt/Physics/PhysicsStepListener.h:34:17: note: hidden overloaded virtual function 'JPH::PhysicsStepListener::OnStep' declared here: different number of parameters (1 vs 2)
   34 |         virtual void                    OnStep(const PhysicsStepListenerContext &inContext) = 0;
      |                                         ^
In file included from build_0903f6c2/.gens/NazaraPhysics3D/macosx/unity_build/unity_1.cpp:17:
build_0903f6c2/.gens/NazaraPhysics3D/macosx/unity_build/../../../../../src/Nazara/Physics3D/PhysWorld3D.cpp:431:29: error: field type 'PhysWorld3D::StepListener' is an abstract class
  431 |                 PhysWorld3D::StepListener stepListener;
      |                                           ^
/Users/alspin/.xmake/packages/j/joltphysics/v5.2.0/2b4e0d7640294b148433eaa2af888e86/include/Jolt/Physics/PhysicsStepListener.h:34:17: note: unimplemented pure virtual method 'OnStep' in 'StepListener'
   34 |         virtual void                    OnStep(const PhysicsStepListenerContext &inContext) = 0;
`

**Comment by SirLynix** [comment]
C'est corrigé sur main mais pas encore dans le package, je vais bientôt le mettre à jour.

Si besoin d'un hotfix tu peux normalement mettre `add_requireconfs("nazaraengine.joltphysics", { version = "v5.1.0", override = true })` dans ton xmake.lua

**Comment by devalexxx** [comment]
Ca garde jolt 5.2, je vais attendre la maj et je fermerai l'issue si c'est good

**Comment by SirLynix** [comment]
Le package vient d'être mis à jour, si tu me confirmes que c'est bon je fermerais l'issue. 😄

**Comment by devalexxx** [comment]
C'est bon, plus de problème de compilation

**Comment by SirLynix** [comment]
Merci !
