### ISSUE TITLE
Portage Mac OSX

### ISSUE THREAD

**Issue by GuillaumeBelz** [NazaraEngine/NazaraEngine#97]
Depend de https://github.com/DigitalPulseSoftware/NazaraEngine/issues/96 

Sous-taches :
- [ ] Core
- [ ] Network
- [ ] Renderer
- [ ] Utility

**Comment by DPSLynix** [comment]
Normalement le Core et le Network sont supportés par OS X, car Posix, mais je n'ai pas de machine pour tester/développer

**Comment by GuillaumeBelz** [comment]
Pour le moment, le build passe pas. Parfois, ce sont juste des problèmes de noms de fonctions qui changent, mais parfois il faut réécrire le code (par exemple pour la partie GL).
Je verrais pour faire un premier commit en corrigeant le build, et en créant les classes Impl mais sans les implémenter.

**Comment by DPSLynix** [comment]
À voir aussi du côté d'Objective C/Swift, qui change un peu sous OS X/iOS.

**Comment by SirLynix** [comment]
Done
